#!/bin/sh

# run background mesh
blockMesh | tee log.blockMesh
checkMesh | tee log.checkMesh_block

# to extract features if needed
#surfaceFeatureExtract | tee log.surfaceFeatureExtract

# run snappyHexMesh 
decomposePar | tee log.decomposePar
mpirun -np 32 snappyHexMesh -overwrite -parallel | tee log.snappyHexMesh
reconstructParMesh -constant | tee log.reconstructParMesh
rm -rf processor*
checkMesh | tee log.checkMesh_snappy

#------------------------------------------------------------------------------
